# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jiaoce',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carname', models.TextField()),
                ('cardata', models.TextField()),
                ('carurl', models.TextField()),
                ('cartu', models.TextField()),
                ('carjiage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mianbaoce',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carname', models.TextField()),
                ('cardata', models.TextField()),
                ('carurl', models.TextField()),
                ('cartu', models.TextField()),
                ('carjiage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mpvce',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carname', models.TextField()),
                ('cardata', models.TextField()),
                ('carurl', models.TextField()),
                ('cartu', models.TextField()),
                ('carjiage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='paoce',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carname', models.TextField()),
                ('cardata', models.TextField()),
                ('carurl', models.TextField()),
                ('cartu', models.TextField()),
                ('carjiage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pikace',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carname', models.TextField()),
                ('cardata', models.TextField()),
                ('carurl', models.TextField()),
                ('cartu', models.TextField()),
                ('carjiage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='xinnengyuance',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carname', models.TextField()),
                ('cardata', models.TextField()),
                ('carurl', models.TextField()),
                ('cartu', models.TextField()),
                ('carjiage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='yueyece',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carname', models.TextField()),
                ('cardata', models.TextField()),
                ('carurl', models.TextField()),
                ('cartu', models.TextField()),
                ('carjiage', models.TextField()),
            ],
        ),
    ]
