version: '2'

services:
  nginx:
    image: nginx
    depends_on:
      - api
    volumes:
      - ./logs:/var/logs
      - ./web/dist:/var/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9080:9080"
    links:
      - api
  api:
    build: api
    command: python3 manage.py runserver 0.0.0.0:9090
    volumes:
      - ./api:/code
    env_file: .env
