"""
Django settings for tiku_api project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os

import pymysql

# ETCD_HOST = os.environ['ETCD_HOST']
# ETCD_PORT = int(os.environ['ETCD_PORT'])
# ETCD_USERNAME = os.environ.get('ETCD_USERNAME')
# ETCD_PASSWORD = os.environ.get('ETCD_PASSWORD')
# ETCD_DB = os.environ.get('ETCD_DB')



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

pymysql.install_as_MySQLdb()



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k*+7si0s#uepmo0ak9#e@3!m1p6k_$+91$#hpj$7i&n8risets'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG=False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
# import json
# _DIR = os.path.dirname(os.path.abspath(__file__))
# CONFIG_FILE_PATH = os.path.join(_DIR, 'config')
# config = json.load(open(CONFIG_FILE_PATH))
#

DB_ENGINE_MYSQL = 'django.db.backends.mysql'
DB_ENGINE_MYSQL_POOL = 'django_mysqlpool.backends.mysqlpool'
MYSQLPOOL_ARGUMENTS = {
    'recycle': 30,
    'pool_size': 128,
    'max_overflow': 10,
    'timeout': 5,
    'use_threadlocal': True,
}

ETCD_HOST='172.16.16.17'
ETCD_PORT='3306'
ETCD_USERNAME='wangjunling'
ETCD_PASSWORD='Aftwjl3BwNe9D'
ETCD_DB='test'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': ETCD_DB,
        'USER':ETCD_USERNAME,
        'PASSWORD':ETCD_PASSWORD,
        'HOST':ETCD_HOST,
        'PORT':ETCD_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
# is_https
SECURE_PROXY_SSL_HEADER = ('HTTP_URLPREFIX', 'https')

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


